## WORD EMBEDDING :GENSIM

Gensim is a Python library for topic modelling, document indexing and similarity retrieval with large corpora. Target audience is the natural language processing (NLP) and information retrieval (IR) community.



In [1]:
import numpy as np

In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [3]:
from sklearn.decomposition import PCA

In [4]:
!pip install gensim

In [7]:
!python -m pip install -U gensim

import gensim.downloader as api
from gensim.models import KeyedVectors


In [8]:
model=api.load('glove-wiki-gigaword-100') #selected corpus

[==========----------------------------------------] 21.2% 27.1/128.1MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[====================------------------------------] 41.8% 53.5/128.1MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[=================================-----------------] 66.3% 84.9/128.1MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[=============================================-----] 91.4% 117.1/128.1MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[==================================================] 100.0% 128.1/128.1MB downloaded


In [9]:
print(type(model))

<class 'gensim.models.keyedvectors.KeyedVectors'>


The model is ready and we can see the word embeddings. Here are some examples:

In [10]:
model['bread']

array([-0.66146  ,  0.94335  , -0.72214  ,  0.17403  , -0.42524  ,
        0.36303  ,  1.0135   , -0.14802  ,  0.25817  , -0.20326  ,
       -0.64338  ,  0.16632  ,  0.61518  ,  1.397    , -0.094506 ,
        0.0041843, -0.18976  , -0.55421  , -0.39371  , -0.22501  ,
       -0.34643  ,  0.32076  ,  0.34395  , -0.7034   ,  0.23932  ,
        0.69951  , -0.16461  , -0.31819  , -0.34034  , -0.44906  ,
       -0.069667 ,  0.35348  ,  0.17498  , -0.95057  , -0.2209   ,
        1.0647   ,  0.23231  ,  0.32569  ,  0.47662  , -1.1206   ,
        0.28168  , -0.75172  , -0.54654  , -0.66337  ,  0.34804  ,
       -0.69058  , -0.77092  , -0.40167  , -0.069351 , -0.049238 ,
       -0.39351  ,  0.16735  , -0.14512  ,  1.0083   , -1.0608   ,
       -0.87314  , -0.29339  ,  0.68278  ,  0.61634  , -0.088844 ,
        0.88094  ,  0.099809 , -0.27161  , -0.58026  ,  0.50364  ,
       -0.93814  ,  0.67576  , -0.43124  , -0.10517  , -1.2404   ,
       -0.74353  ,  0.28637  ,  0.29012  ,  0.89377  ,  0.6740

In [12]:
model['croissant']

array([-0.25144  ,  0.52157  , -0.75452  ,  0.28039  , -0.31388  ,
        0.274    ,  1.1971   , -0.10519  ,  0.82544  , -0.33398  ,
       -0.21417  ,  0.22216  ,  0.14982  ,  0.47384  ,  0.41984  ,
        0.69397  , -0.25999  , -0.44414  ,  0.58296  , -0.30851  ,
       -0.076455 ,  0.33468  ,  0.28055  , -0.99012  ,  0.30349  ,
        0.39128  ,  0.031526 , -0.095395 , -0.004745 , -0.81347  ,
        0.27869  , -0.1812   ,  0.14632  , -0.42186  ,  0.13857  ,
        1.139    ,  0.14925  , -0.051459 ,  0.37875  , -0.2613   ,
        0.011081 , -0.28881  , -0.38662  , -0.3135   , -0.1954   ,
        0.19248  , -0.52995  , -0.40674  , -0.25159  ,  0.06272  ,
       -0.32724  ,  0.28374  , -0.2155   , -0.061832 , -0.50134  ,
        0.0093959,  0.30715  ,  0.3873   , -0.74554  , -0.45947  ,
        0.40032  , -0.1378   , -0.26968  , -0.3946   , -0.64876  ,
       -0.47149  , -0.085536 ,  0.092795 , -0.034018 , -0.61906  ,
        0.19123  ,  0.20563  ,  0.29056  , -0.010908 ,  0.1531

The most similar and least similar words :

In [15]:
model.most_similar('bread')

[('flour', 0.7654520869255066),
 ('baked', 0.7607272863388062),
 ('cake', 0.7605516910552979),
 ('loaf', 0.7457114458084106),
 ('toast', 0.7397798895835876),
 ('cheese', 0.7374635338783264),
 ('potato', 0.7367483973503113),
 ('butter', 0.7279618978500366),
 ('potatoes', 0.7085272669792175),
 ('pasta', 0.7071877717971802)]

In [16]:
model['flour']

array([-1.0214   ,  0.64669  , -0.81953  , -0.09019  , -0.6946   ,
       -0.0056647,  1.1741   ,  0.37611  ,  0.29266  ,  0.18367  ,
        0.18059  , -0.87828  ,  0.29302  ,  1.1791   , -0.099289 ,
       -0.38544  , -0.27431  , -0.15229  , -0.025112 , -0.83009  ,
       -0.45715  ,  0.93499  ,  0.34476  , -0.5069   , -0.049767 ,
        0.43931  , -0.10244  ,  0.15289  , -0.37199  ,  0.26704  ,
       -0.51315  ,  0.0085009, -0.081211 , -0.60786  , -0.84611  ,
        0.36856  ,  1.069    ,  0.71025  ,  0.15542  , -0.18672  ,
       -0.29141  , -1.6818   , -0.43828  , -0.85003  ,  0.52986  ,
       -0.18132  , -1.0381   , -0.43679  , -0.035185 , -0.54077  ,
       -1.0855   ,  0.33895  ,  0.53353  ,  1.5009   , -0.6338   ,
        0.0055149, -1.0831   ,  0.18951  ,  0.56261  , -0.67866  ,
        0.56665  , -0.29713  ,  0.037538 , -0.036634 ,  0.76163  ,
       -1.1375   ,  0.81612  ,  0.022784 , -0.17337  , -0.86987  ,
       -0.88325  , -0.21943  , -0.042224 ,  1.222    ,  1.2104

In [17]:
model.most_similar(negative='happy')

[('socionics', 0.5758118629455566),
 ('francheville', 0.5602913498878479),
 ('bb94', 0.5592160820960999),
 ('westendorf', 0.5574142336845398),
 ('darban', 0.556814968585968),
 ('bhaktavatsalam', 0.5555770397186279),
 ('ink-jet', 0.553968071937561),
 ('malkawi', 0.5515477061271667),
 ('busybox', 0.5482652187347412),
 ('dhimitër', 0.5443779230117798)]

In [18]:
model.most_similar('happy')

[("'m", 0.8413287401199341),
 ('feel', 0.8132575750350952),
 ("'re", 0.804808497428894),
 ('i', 0.7938276529312134),
 ("'ll", 0.7916273474693298),
 ('really', 0.7903971076011658),
 ('glad', 0.7833361029624939),
 ('good', 0.7821646332740784),
 ('we', 0.7808917164802551),
 ('sure', 0.7788467407226562)]

For more complex similarity: 

In [23]:
result=model.most_similar(positive=['woman','king'],negative='man')

In [24]:
result[0]

('queen', 0.7698541283607483)

In [26]:
def analogy(x1,x2,y1):
    result=model.most_similar(positive=[y1,x2],negative=x1)
    return result[0][0]

In [27]:
analogy('man','king','woman')

'queen'